<?php

namespace Database\Seeders;

use App\Models\Penandatangan;
use Illuminate\Database\Seeder;

class PenandatanganSeeder extends Seeder
{
    public function run(): void
    {
        $signers = [
            // ── Kategori 1: Pejabat Berwenang ─────────────────────────────
            [
                'kategori'         => 'pejabat_wenang',
                'nama'             => 'Ir. BANI ISPRIYANTO, M.M.',
                'nip'              => '196904101995031002',
                'jabatan'          => 'Kepala Dinas ',
                'pangkat_golongan' => 'Pembina Utama Muda (IV/c)',
                'is_default'       => true,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'pejabat_wenang',
                'nama'             => 'RAHMAT MIRZANI DJAUSAL, S.T., M.M.',
                'nip'              => '-',
                'jabatan'          => 'Gubernur Lampung',
                'pangkat_golongan' => 'Pejabat Negara',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'pejabat_wenang',
                'nama'             => 'Dr. MARINDO KURNIAWAN, S.T., M.M.',
                'nip'              => '198012062002121010',
                'jabatan'          => 'Sekretaris Daerah Provinsi Lampung',
                'pangkat_golongan' => 'Pembina Utama (IV/e)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'pejabat_wenang',
                'nama'             => 'RENDY RISWANDI, S.STP., M.Si.',
                'nip'              => '197705261997121001',
                'jabatan'          => 'Kepala Badan Kepegawaian Daerah Provinsi Lampung',
                'pangkat_golongan' => 'Pembina Utama Muda (IV/c)',
                'is_default'       => false,
                'is_active'        => true,
            ],

            // ── Kategori 2: Atasan Langsung ──────────────────────────────
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'Ir. BANI ISPRIYANTO, M.M.',
                'nip'              => '196904101995031002',
                'jabatan'          => 'Kepala Dinas ',
                'pangkat_golongan' => 'Pembina Utama Muda (IV/c)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'A. FAISAL, A.Pi.',
                'nip'              => '197402031999031006',
                'jabatan'          => 'Sekretaris Dinas ',
                'pangkat_golongan' => 'Pembina Tk. I (IV/b)',
                'is_default'       => true,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'HARDIAN SYLVANANDRA PRAYITNO, S.Pi., M.M.',
                'nip'              => '198503222008041001',
                'jabatan'          => 'Kepala Bidang Pengawasan Sumber Daya Kelautan dan Perikanan',
                'pangkat_golongan' => 'Pembina (IV/a)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'SADARIAH, S.P., M.M.',
                'nip'              => '197009301996022001',
                'jabatan'          => 'Kepala Bidang Pengelolaan Ruang Laut',
                'pangkat_golongan' => 'Pembina Tk. I (IV/b)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'Dr.NAZDAN, S.Pi., M.P.',
                'nip'              => '197306102002121002',
                'jabatan'          => 'Kepala Bidang Perikanan Budidaya dan Penguatan Daya Saing',
                'pangkat_golongan' => 'Pembina Tk. I (IV/b)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'SRI RIHATUN DHAMAYANTI, S.Pi., M.M.',
                'nip'              => '197307172000032004',
                'jabatan'          => 'Kepala UPTD Penerapan Mutu Hasil Perikanan',
                'pangkat_golongan' => 'Pembina Tk. I (IV/b)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'ZAINAL K., S.Pi., M.Ling.',
                'nip'              => '197104051997031007',
                'jabatan'          => 'Kepala UPTD Pelabuhan Perikanan Labuhan Maringgai',
                'pangkat_golongan' => 'Pembina Tk. I (IV/b)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'AHMAD DARMA HABIBILLAH, S.Pi., M.E.',
                'nip'              => '198006182005011007',
                'jabatan'          => 'Kepala UPTD Pelabuhan Perikanan Lempasing',
                'pangkat_golongan' => 'Pembina (IV/a)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'SUKARSONO, S.Pi.',
                'nip'              => '197111081999031004',
                'jabatan'          => 'Kepala UPTD Pelabuhan Perikanan Kota Agung',
                'pangkat_golongan' => 'Pembina (IV/a)',
                'is_default'       => false,
                'is_active'        => true,
            ],
            [
                'kategori'         => 'atasan_langsung',
                'nama'             => 'ZULHAIDIR, S.P., M.Si.',
                'nip'              => '197204292000031003',
                'jabatan'          => 'Kepala UPTD Pelabuhan Perikanan Kalianda',
                'pangkat_golongan' => 'Pembina Tk. I (IV/b)',
                'is_default'       => false,
                'is_active'        => true,
            ],

            // ── Kategori 3: Pejabat Pengawas ──────────────────────────────
            [
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'IMAM KOMARITA, S.Pi., M.Si.',
    'nip'              => '198601302011011004',
    'jabatan'          => 'Kepala Sub Bagian Umum dan Kepegawaian Sekretariat Dinas',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => true,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'SRI HARTATI, S.Pi., M.Ling.',
    'nip'              => '197704132010012004',
    'jabatan'          => 'Kepala Sub Bagian Keuangan dan Aset Sekretariat Dinas',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'FAHRUL ROZI, S.E.',
    'nip'              => '198009022006041008',
    'jabatan'          => 'Kepala Sub Bagian Tata Usaha UPTD Pelabuhan Perikanan Lempasing',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'SARNUBI, S.Sos.',
    'nip'              => '196908242003121001',
    'jabatan'          => 'Kepala Sub Bagian Tata Usaha UPTD Pelabuhan Perikanan Labuhan Maringgai',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'RIFKI ANDRIAS, S.H., M.H.',
    'nip'              => '198503092009021003',
    'jabatan'          => 'Kepala Sub Bagian Tata Usaha UPTD Pelabuhan Perikanan Kota Agung',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'ZULKIFLI MASRURI, S.A.N., M.M.',
    'nip'              => '198010062002121003',
    'jabatan'          => 'Kepala Sub Bagian Tata Usaha UPTD Penerapan Mutu Hasil Perikanan',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'HERU ROMADI, S.E., M.M.',
    'nip'              => '197108231998031007',
    'jabatan'          => 'Kepala Seksi Pengusahaan UPTD Pelabuhan Perikanan Lempasing',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'UMMU HANNY, S.Pi., M.Si.',
    'nip'              => '198007092006042008',
    'jabatan'          => 'Kepala Seksi Sarana dan Prasarana UPTD Pelabuhan Perikanan Kota Agung',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'RENI SRI MULYANI, S.ST., M.M.',
    'nip'              => '197309091993032004',
    'jabatan'          => 'Kepala Seksi Pengembangan Hasil Perikanan UPTD Penerapan Mutu Hasil Perikanan',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'OKTA LINDRA SAPUTRA, S.St.Pi., M.M.',
    'nip'              => '198010262010011008',
    'jabatan'          => 'Kepala Seksi Sarana dan Prasarana UPTD Pelabuhan Perikanan Lempasing',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'RR. RETNO KOOSTATI, S.Pi., M.Ling.',
    'nip'              => '197008242005012011',
    'jabatan'          => 'Kepala Seksi Pengujian dan Monitoring UPTD Penerapan Mutu Hasil Perikanan',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'DEDI SUKMA SUPRIATNA, S.St.Pi., M.M.',
    'nip'              => '198607152010011013',
    'jabatan'          => 'Kepala Seksi Sarana dan Prasarana UPTD Pelabuhan Perikanan Labuhan Maringgai',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'FREDY AGUSTA, S.Pi., M.Si.',
    'nip'              => '198508022010011012',
    'jabatan'          => 'Kepala Seksi Pengusahaan UPTD Pelabuhan Perikanan Labuhan Maringgai',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'YENI MELIA, S.E., M.M.',
    'nip'              => '198106022010012003',
    'jabatan'          => 'Kepala Seksi Pengusahaan UPTD Pelabuhan Perikanan Kota Agung',
    'pangkat_golongan' => 'Pembina (IV/a)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'LOEKITO AGUNG PAMBUDI, S.Pi.',
    'nip'              => '197703132010011006',
    'jabatan'          => 'Kepala Seksi Pelayanan dan Pengendalian Mutu Perbenihan UPTD Balai Perikanan Budidaya Air Laut dan Payau',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'DONI WIDYASMORO, S.Pi., M.Si.',
    'nip'              => '198310242010011011',
    'jabatan'          => 'Kepala Seksi Sarana dan Prasarana UPTD Pelabuhan Perikanan Kalianda',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => false,
    'is_active'        => true,
],
[
    'kategori'         => 'pejabat_pengawas',
    'nama'             => 'NELSON PARIZAL, S.Pi.',
    'nip'              => '197908242010011002',
    'jabatan'          => 'Kepala Seksi Pengusahaan UPTD Pelabuhan Perikanan Kalianda',
    'pangkat_golongan' => 'Penata Tk. I (III/d)',
    'is_default'       => false,
    'is_active'        => true,
],
        ];

        foreach ($signers as $data) {
            Penandatangan::updateOrCreate(
                [
                    'nip'      => $data['nip'],
                    'kategori' => $data['kategori'],
                ],
                $data
            );
        }
    }
}
